# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: lovebank_development
  pool: 5
  username: lovebank

test:
  adapter: postgresql
  encoding: unicode
  database: lovebank_test
  pool: 5
  username: lovebank

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV["SOME_OTHER_URL"] %>
  pool: 5
  timeout: 5000
